image: node:latest

cache: 
  paths: 
    - node_modules/

pages: 
  script:
    - npm install --progress=false --no-optional
    - npm run build
    - rm -rf public/*
    - mv dist/* public
  artifacts:
    expire_in: 3 days
    paths:
      - public
  only: 
    - master